### ISSUE TITLE
Save images in cpmsg/movmsg to a cache and reupload

### ISSUE THREAD

**Issue by telugu-boy** [tripulse/trigonopulse#8]
movmsg might delete the image rendering the URL invalid, a solution is to save the images to memory and upload them again. They can be cleared from memory on successful upload.

**Comment by tripulse** [comment]
That'll be costly of bandwidth, but yes that is a problem. In addition to this there should be an option to control this semantic.

**Comment by tripulse** [comment]
This is memory efficient, not bandwidth though.
https://discordpy.readthedocs.io/en/stable/api.html?highlight=attachment#discord.Attachment.to_file

**Comment by telugu-boy** [comment]
yyyuz breh mek duh shi upshan '-' ah gut uhnlimtud ch0d0vidth frfrfrfr '------v='

**Comment by tripulse** [comment]
guddu breh '-v
